#spring.datasource.username=test
#spring.datasource.password=test

#spring.datasource.url=jdbc:hsqldb:mem:main
#spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver
#spring.secondaryDatasource.url=jdbc:hsqldb:mem:secondary

#logging.level.com.datasources=DEBUG
#spring.jpa.hibernate.ddl-auto=update

spring:
  profiles.active: default,secondary
  datasource:
    username: main
    password: main
    url: jdbc:hsqldb:mem:main
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
---
spring:
  profiles: secondary
  datasource:
    username: secondary
    password: secondary
    url: jdbc:hsqldb:mem:secondary